// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyService.Data;

namespace PolicyService.Data.Migrations
{
    [DbContext(typeof(PolicyServiceContext))]
    partial class PolicyServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyService.Data.Entities.ConsumerPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptedQuote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssuredSum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BusinessValue")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConsumerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PropertyValue")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumerPolicies");
                });

            modelBuilder.Entity("PolicyService.Data.Entities.PolicyMaster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AssuredSum")
                        .HasColumnType("float");

                    b.Property<string>("BaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BusinessValue")
                        .HasColumnType("bigint");

                    b.Property<string>("ConsumerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PropertyValue")
                        .HasColumnType("bigint");

                    b.Property<string>("Tenure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolicyMasters");

                    b.HasData(
                        new
                        {
                            Id = "P01",
                            AssuredSum = 400000.0,
                            BaseLocation = "Chennai",
                            BusinessValue = 8L,
                            ConsumerType = "Owner",
                            PropertyType = "Building",
                            PropertyValue = 5L,
                            Tenure = "3 year",
                            Type = "Replacement"
                        },
                        new
                        {
                            Id = "P02",
                            AssuredSum = 20000000.0,
                            BaseLocation = "Chennai",
                            BusinessValue = 9L,
                            ConsumerType = "Owner",
                            PropertyType = "Factory Equipment",
                            PropertyValue = 10L,
                            Tenure = "1 year",
                            Type = "Replacement"
                        },
                        new
                        {
                            Id = "P03",
                            AssuredSum = 200000.0,
                            BaseLocation = "Pune",
                            BusinessValue = 7L,
                            ConsumerType = "Owner",
                            PropertyType = "Property in Transit",
                            PropertyValue = 8L,
                            Tenure = "1 week",
                            Type = "Pay Back"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
